spring.application.name=MyEplPredictor

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Important for Render's SSL requirement
spring.datasource.hikari.connection-timeout=30000

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
# hope this works oh

# Replace this value with a securely stored 256-bit Base64 key in production
jwt.secret=MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFk=
jwt.expiration-ms=3600000
bet365.api-key=4075e00cb3msh805505ba760fa9dp130d32jsne9f9ddcbc46a
bet365.base-url=https://bet36528.p.rapidapi.com
bet365.tournament-id=17

# latest

DATABASE_PASSWORD=i9tj8thXK3ta3Y0ZuSjS4lJJDANdbUj7
DATABASE_USERNAME=awwalspring_user
DATABASE_URL=jdbc:postgresql://dpg-d6iju7ngi27c738jjt5g-a.oregon-postgres.render.com/awwalspring?sslmode=require
server.port=${PORT:8080}

spring.cache.type=simple

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
